// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfozzgpywruxtnqlypxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indmb3p6Z3B5d3J1eHRucWx5cHhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MTMyNTgsImV4cCI6MjA2NTE4OTI1OH0.WwQ0U0-kyXB7PmXP4U6fCcq1rYewK70dc64880cNob4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);